import PDFDocument from "pdfkit";
import { Response } from "express";
import { prisma } from "../../config/database";
import { AppError } from "../../utils/app-error";
import { env } from "../../config/env";

// ─── Helpers ──────────────────────────────────────────────────

const COLORS = {
  primary:   "#1e3a5f",
  secondary: "#2563eb",
  accent:    "#f59e0b",
  text:      "#1f2937",
  muted:     "#6b7280",
  light:     "#f3f4f6",
  white:     "#ffffff",
  success:   "#16a34a",
  danger:    "#dc2626",
} as const;

function streamToResponse(doc: PDFKit.PDFDocument, res: Response, filename: string) {
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
  doc.pipe(res);
}

function drawHeader(doc: PDFKit.PDFDocument, title: string, subtitle?: string) {
  // Header background
  doc.rect(0, 0, doc.page.width, 90).fill(COLORS.primary);

  // College name
  doc
    .fillColor(COLORS.white)
    .fontSize(20)
    .font("Helvetica-Bold")
    .text(env.COLLEGE_NAME, 40, 20, { align: "center" });

  // Document title
  doc
    .fontSize(12)
    .font("Helvetica")
    .text(title, 40, 48, { align: "center" });

  if (subtitle) {
    doc.fontSize(10).text(subtitle, 40, 66, { align: "center" });
  }

  // Reset color
  doc.fillColor(COLORS.text);
  doc.moveDown(0.5);
}

function drawDivider(doc: PDFKit.PDFDocument, y?: number) {
  const posY = y ?? doc.y;
  doc
    .moveTo(40, posY)
    .lineTo(doc.page.width - 40, posY)
    .strokeColor(COLORS.light)
    .lineWidth(1)
    .stroke();
}

function drawLabelValue(
  doc:   PDFKit.PDFDocument,
  label: string,
  value: string,
  x:     number,
  y:     number,
  width  = 230
) {
  doc
    .fontSize(9)
    .font("Helvetica-Bold")
    .fillColor(COLORS.muted)
    .text(label.toUpperCase(), x, y, { width });

  doc
    .fontSize(11)
    .font("Helvetica")
    .fillColor(COLORS.text)
    .text(value || "—", x, y + 13, { width });
}

function drawFooter(doc: PDFKit.PDFDocument) {
  const pageH = doc.page.height;
  doc
    .rect(0, pageH - 40, doc.page.width, 40)
    .fill(COLORS.light);

  doc
    .fillColor(COLORS.muted)
    .fontSize(8)
    .font("Helvetica")
    .text(
      `Generated by ${env.COLLEGE_NAME} — ${new Date().toLocaleString()}  |  This is a system-generated document.`,
      40,
      pageH - 27,
      { align: "center" }
    );
}

// ─── FEE RECEIPT PDF ──────────────────────────────────────────

export async function generateFeeReceipt(invoiceId: string, res: Response) {
  const invoice = await prisma.feeInvoice.findUnique({
    where: { id: invoiceId },
    include: {
      studentProfile: {
        include: {
          program:    { include: { department: { select: { name: true } } } },
          user:       { select: { username: true, email: true } },
        },
      },
      payments:  { orderBy: { paidAt: "asc" } },
      discounts: true,
    },
  });

  if (!invoice) throw AppError.notFound("Invoice not found");

  const student = invoice.studentProfile;
  const doc     = new PDFDocument({ size: "A4", margin: 40 });

  streamToResponse(doc, res, `receipt-${invoice.invoiceNo}.pdf`);

  // ── Header ────────────────────────────────────────────────
  drawHeader(doc, "FEE RECEIPT", `Invoice No: ${invoice.invoiceNo}`);

  // ── Student Info ──────────────────────────────────────────
  const infoY = 110;
  doc
    .rect(40, infoY, doc.page.width - 80, 80)
    .fill(COLORS.light)
    .fillColor(COLORS.text);

  drawLabelValue(doc, "Student Name",    `${student.firstName} ${student.lastName}`, 55, infoY + 10, 200);
  drawLabelValue(doc, "Registration No", student.registrationNo,                    285, infoY + 10, 160);
  drawLabelValue(doc, "Program",         student.program.name,                       55, infoY + 45, 200);
  drawLabelValue(doc, "Department",      student.program.department?.name ?? "—",   285, infoY + 45, 160);

  doc.y = infoY + 100;

  // ── Invoice Details ───────────────────────────────────────
  if (invoice.semester) {
    doc
      .fontSize(10)
      .font("Helvetica-Bold")
      .fillColor(COLORS.primary)
      .text(`Semester: ${invoice.semester}`, 40, doc.y);
    doc.moveDown(0.3);
  }

  drawDivider(doc);
  doc.moveDown(0.5);

  // ── Financial Summary ─────────────────────────────────────
  const summaryX = doc.page.width - 220;
  const rows: [string, string, string?][] = [
    ["Total Amount",    `Rs. ${invoice.totalAmount.toLocaleString()}`],
    ["Discount",        `Rs. ${invoice.discountAmount.toLocaleString()}`, COLORS.success],
    ["Amount Paid",     `Rs. ${invoice.paidAmount.toLocaleString()}`,    COLORS.success],
    ["Due Amount",      `Rs. ${invoice.dueAmount.toLocaleString()}`,     invoice.dueAmount > 0 ? COLORS.danger : COLORS.success],
  ];

  let rowY = doc.y;
  for (const [label, value, color] of rows) {
    doc
      .fontSize(10)
      .font("Helvetica")
      .fillColor(COLORS.muted)
      .text(label, summaryX, rowY, { width: 100 });

    doc
      .fontSize(10)
      .font("Helvetica-Bold")
      .fillColor(color ?? COLORS.text)
      .text(value, summaryX + 100, rowY, { width: 100, align: "right" });

    rowY += 22;
  }

  // Status badge
  const statusColor = invoice.status === "PAID" ? COLORS.success :
                      invoice.status === "OVERDUE" ? COLORS.danger : COLORS.accent;
  doc
    .rect(summaryX, rowY + 5, 200, 26)
    .fill(statusColor);
  doc
    .fillColor(COLORS.white)
    .fontSize(11)
    .font("Helvetica-Bold")
    .text(`STATUS: ${invoice.status}`, summaryX, rowY + 11, { width: 200, align: "center" });

  doc.y = rowY + 50;
  drawDivider(doc);
  doc.moveDown(0.5);

  // ── Payment History ───────────────────────────────────────
  if (invoice.payments.length > 0) {
    doc
      .fontSize(11)
      .font("Helvetica-Bold")
      .fillColor(COLORS.primary)
      .text("Payment History", 40, doc.y);

    doc.moveDown(0.4);

    // Table header
    const colX = [40, 160, 280, 380, 480];
    const headers = ["Date", "Amount", "Method", "Transaction ID"];

    doc
      .rect(40, doc.y, doc.page.width - 80, 22)
      .fill(COLORS.primary);

    doc.fillColor(COLORS.white).fontSize(9).font("Helvetica-Bold");
    headers.forEach((h, i) => {
      doc.text(h, colX[i] + 5, doc.y - 17, { width: colX[i + 1] - colX[i] - 5 });
    });

    doc.moveDown(0.2);

    // Table rows
    for (const [idx, p] of invoice.payments.entries()) {
      const rowBg = idx % 2 === 0 ? COLORS.white : COLORS.light;
      doc.rect(40, doc.y, doc.page.width - 80, 20).fill(rowBg);

      doc.fillColor(COLORS.text).fontSize(9).font("Helvetica");
      const rowTop = doc.y + 5;
      doc.text(new Date(p.paidAt).toLocaleDateString(),  colX[0] + 5, rowTop, { width: 115 });
      doc.text(`Rs. ${p.amount.toLocaleString()}`,       colX[1] + 5, rowTop, { width: 115 });
      doc.text(p.method,                                  colX[2] + 5, rowTop, { width: 95 });
      doc.text(p.transactionId ?? "—",                   colX[3] + 5, rowTop, { width: 100 });

      doc.moveDown(0.7);
    }
  }

  // ── Due Date ──────────────────────────────────────────────
  doc.moveDown(0.5);
  doc
    .fontSize(9)
    .font("Helvetica")
    .fillColor(COLORS.muted)
    .text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}`, 40, doc.y);

  drawFooter(doc);
  doc.end();
}

// ─── REPORT CARD PDF ──────────────────────────────────────────

export async function generateReportCard(userId: string, semesterId: string, res: Response) {
  const studentProfile = await prisma.studentProfile.findUnique({
    where: { userId },
    include: {
      program:    { include: { department: { select: { name: true } } } },
      user:       { select: { username: true, email: true } },
    },
  });

  if (!studentProfile) throw AppError.notFound("Student not found");

  const semester = await prisma.semester.findUnique({
    where: { id: semesterId },
    include: { academicSession: { include: { program: true } } },
  });

  if (!semester) throw AppError.notFound("Semester not found");

  // Get published results for this student in this semester
  const results = await prisma.examResult.findMany({
    where: {
      studentProfileId: studentProfile.id,
      isPublished:      true,
      exam: { section: { semesterId } },
    },
    include: {
      exam: {
        include: {
          section: {
            include: { course: { select: { name: true, code: true, creditHours: true } } },
          },
        },
      },
    },
    orderBy: { exam: { section: { course: { code: "asc" } } } },
  });

  // Get attendance summary for this semester
  const attendanceSummary = await prisma.attendanceRecord.findMany({
    where: {
      studentProfileId: studentProfile.id,
      attendanceSession: { section: { semesterId } },
    },
    select: { status: true, attendanceSession: { select: { sectionId: true } } },
  });

  const totalClasses = attendanceSummary.length;
  const present      = attendanceSummary.filter(
    (a: { status: string }) => a.status === "PRESENT" || a.status === "LATE"
  ).length;
  const attendancePct = totalClasses > 0 ? Math.round((present / totalClasses) * 100) : 0;

  // Group results by course
  const courseMap = new Map<string, {
    course: { name: string; code: string; creditHours: number };
    exams:  typeof results;
  }>();

  for (const r of results) {
    const code = r.exam.section.course.code;
    if (!courseMap.has(code)) {
      courseMap.set(code, { course: r.exam.section.course, exams: [] });
    }
    courseMap.get(code)!.exams.push(r);
  }

  const courseReports = Array.from(courseMap.values()).map((entry) => {
    const totalMarks   = entry.exams.reduce((s: number, e: { exam: { totalMarks: number } }) => s + e.exam.totalMarks, 0);
    const obtainedMarks = entry.exams
      .filter((e: { isAbsent: boolean }) => !e.isAbsent)
      .reduce((s: number, e: { marksObtained: number }) => s + e.marksObtained, 0);
    const percentage   = totalMarks > 0 ? Math.round((obtainedMarks / totalMarks) * 100) : 0;
    const grade        = getLetterGrade(percentage);

    return { ...entry, obtainedMarks, totalMarks, percentage, grade };
  });

  const overallPct = courseReports.length > 0
    ? Math.round(courseReports.reduce((s, c) => s + c.percentage, 0) / courseReports.length)
    : 0;

  // ── Build PDF ─────────────────────────────────────────────
  const doc = new PDFDocument({ size: "A4", margin: 40 });
  const semLabel = `Semester ${semester.semesterNumber} — ${semester.type} ${
    new Date(semester.startDate).getFullYear()
  }`;

  streamToResponse(
    doc, res,
    `report-card-${studentProfile.registrationNo}-sem${semester.semesterNumber}.pdf`
  );

  drawHeader(doc, "STUDENT REPORT CARD", semLabel);

  // ── Student Info ──────────────────────────────────────────
  const infoY = 110;
  doc.rect(40, infoY, doc.page.width - 80, 80).fill(COLORS.light);

  drawLabelValue(doc, "Name",            `${studentProfile.firstName} ${studentProfile.lastName}`, 55, infoY + 10, 200);
  drawLabelValue(doc, "Registration No", studentProfile.registrationNo,                            285, infoY + 10, 160);
  drawLabelValue(doc, "Program",         studentProfile.program.name,                               55, infoY + 45, 200);
  drawLabelValue(doc, "Department",      studentProfile.program.department?.name ?? "—",           285, infoY + 45, 160);

  doc.y = infoY + 100;

  // ── Results Table ─────────────────────────────────────────
  doc
    .fontSize(11)
    .font("Helvetica-Bold")
    .fillColor(COLORS.primary)
    .text("Course-wise Results", 40, doc.y);
  doc.moveDown(0.4);

  const colX = [40, 130, 310, 380, 430, 480];
  const headers = ["Code", "Course Name", "Obtained", "Total", "%", "Grade"];

  // Table header row
  doc.rect(40, doc.y, doc.page.width - 80, 22).fill(COLORS.primary);
  doc.fillColor(COLORS.white).fontSize(9).font("Helvetica-Bold");
  const hdrY = doc.y + 5;
  headers.forEach((h, i) => {
    doc.text(h, colX[i] + 4, hdrY, { width: (colX[i + 1] ?? doc.page.width - 40) - colX[i] - 4 });
  });
  doc.y += 22;

  // Data rows
  for (const [idx, c] of courseReports.entries()) {
    const bg = idx % 2 === 0 ? COLORS.white : COLORS.light;
    doc.rect(40, doc.y, doc.page.width - 80, 22).fill(bg);

    const gradeColor = c.percentage >= 50 ? COLORS.success : COLORS.danger;
    const rowTop = doc.y + 6;

    doc.fillColor(COLORS.text).fontSize(9).font("Helvetica");
    doc.text(c.course.code,                   colX[0] + 4, rowTop, { width: 86 });
    doc.text(c.course.name,                   colX[1] + 4, rowTop, { width: 176 });
    doc.text(String(c.obtainedMarks),         colX[2] + 4, rowTop, { width: 64 });
    doc.text(String(c.totalMarks),            colX[3] + 4, rowTop, { width: 44 });
    doc.text(`${c.percentage}%`,              colX[4] + 4, rowTop, { width: 44 });
    doc.fillColor(gradeColor).font("Helvetica-Bold");
    doc.text(c.grade,                         colX[5] + 4, rowTop, { width: 36 });

    doc.y += 22;
  }

  doc.moveDown(0.8);
  drawDivider(doc);
  doc.moveDown(0.5);

  // ── Summary Strip ─────────────────────────────────────────
  const stripW  = (doc.page.width - 80) / 3;
  const stripY  = doc.y;
  const strips: [string, string, string][] = [
    ["Overall Percentage", `${overallPct}%`,        overallPct >= 50 ? COLORS.success : COLORS.danger],
    ["Overall Grade",      getLetterGrade(overallPct), overallPct >= 50 ? COLORS.success : COLORS.danger],
    ["Attendance",         `${attendancePct}%`,     attendancePct >= 75 ? COLORS.success : COLORS.danger],
  ];

  strips.forEach(([label, value, color], i) => {
    doc.rect(40 + i * stripW, stripY, stripW - 8, 50).fill(COLORS.light);
    doc
      .fillColor(COLORS.muted).fontSize(8).font("Helvetica")
      .text(label, 48 + i * stripW, stripY + 8, { width: stripW - 16, align: "center" });
    doc
      .fillColor(color).fontSize(18).font("Helvetica-Bold")
      .text(value, 48 + i * stripW, stripY + 22, { width: stripW - 16, align: "center" });
  });

  doc.y = stripY + 65;

  // Pass/Fail status
  const passed = overallPct >= 50 && courseReports.every((c) => c.percentage >= 50);
  doc
    .rect(doc.page.width / 2 - 60, doc.y, 120, 30)
    .fill(passed ? COLORS.success : COLORS.danger);
  doc
    .fillColor(COLORS.white).fontSize(13).font("Helvetica-Bold")
    .text(passed ? "PASS" : "FAIL", doc.page.width / 2 - 60, doc.y + 8,
      { width: 120, align: "center" });

  drawFooter(doc);
  doc.end();
}

function getLetterGrade(pct: number): string {
  if (pct >= 90) return "A+";
  if (pct >= 85) return "A";
  if (pct >= 80) return "A-";
  if (pct >= 75) return "B+";
  if (pct >= 70) return "B";
  if (pct >= 65) return "B-";
  if (pct >= 60) return "C+";
  if (pct >= 55) return "C";
  if (pct >= 50) return "C-";
  if (pct >= 45) return "D";
  return "F";
}
