/** Central query-key factory — keeps invalidation predictable. */
export const queryKeys = {
  auth: { me: ["auth", "me"] as const },
  analytics: {
    overview: ["analytics", "overview"] as const,
    feeTrend: (months: number) => ["analytics", "fees", "trend", months] as const,
    attendanceTrend: (months: number) => ["analytics", "attendance", "trend", months] as const,
    enrollment: ["analytics", "enrollment", "by-program"] as const,
  },
  academic: {
    all: ["academic"] as const,
    departments: ["academic", "departments"] as const,
    programs: ["academic", "programs"] as const,
    sessions: (programId: string) => ["academic", "sessions", programId] as const,
    semesters: (sessionId: string) => ["academic", "semesters", sessionId] as const,
    courses: (params: object) => ["academic", "courses", params] as const,
    sections: (params: object) => ["academic", "sections", params] as const,
    section: (id: string) => ["academic", "section", id] as const,
  },
  students: {
    all: ["students"] as const,
    list: (params: object) => ["students", "list", params] as const,
    detail: (id: string) => ["students", "detail", id] as const,
    picker: (search: string) => ["students", "picker", search] as const,
  },
  staff: {
    all: ["staff"] as const,
    list: (params: object) => ["staff", "list", params] as const,
    detail: (id: string) => ["staff", "detail", id] as const,
    workload: (id: string) => ["staff", "workload", id] as const,
  },
  users: {
    all: ["users"] as const,
    roles: ["users", "roles"] as const,
    list: (params: object) => ["users", "list", params] as const,
  },
  timetable: {
    all: ["timetable"] as const,
    me: ["timetable", "me"] as const,
    section: (id: string) => ["timetable", "section", id] as const,
    teacher: (id: string) => ["timetable", "teacher", id] as const,
  },
  attendance: {
    all: ["attendance"] as const,
    me: (params: object) => ["attendance", "me", params] as const,
    student: (userId: string, params: object) => ["attendance", "student", userId, params] as const,
    sessions: (sectionId: string) => ["attendance", "sessions", sectionId] as const,
    summary: (sectionId: string) => ["attendance", "summary", sectionId] as const,
    session: (id: string) => ["attendance", "session", id] as const,
  },
  exams: {
    all: ["exams"] as const,
    list: (params: object) => ["exams", "list", params] as const,
    detail: (id: string) => ["exams", "detail", id] as const,
    summary: (id: string) => ["exams", "summary", id] as const,
    myGrades: (semesterId: string) => ["exams", "my-grades", semesterId] as const,
  },
  finance: {
    all: ["finance"] as const,
    summary: ["finance", "summary"] as const,
    me: ["finance", "me"] as const,
    feeTypes: ["finance", "fee-types"] as const,
    structures: (programId: string) => ["finance", "structures", programId] as const,
    invoices: (params: object) => ["finance", "invoices", params] as const,
    invoice: (id: string) => ["finance", "invoice", id] as const,
  },
  library: {
    all: ["library"] as const,
    books: (params: object) => ["library", "books", params] as const,
    book: (id: string) => ["library", "book", id] as const,
    active: (params: object) => ["library", "issues", "active", params] as const,
    overdue: ["library", "issues", "overdue"] as const,
    history: (profileId: string) => ["library", "history", profileId] as const,
  },
  complaints: {
    all: ["complaints"] as const,
    categories: ["complaints", "categories"] as const,
    list: (params: object) => ["complaints", "list", params] as const,
    detail: (id: string) => ["complaints", "detail", id] as const,
    stats: ["complaints", "stats"] as const,
  },
  notices: {
    all: ["notices"] as const,
    list: (params: object) => ["notices", "list", params] as const,
    detail: (id: string) => ["notices", "detail", id] as const,
  },
  admissions: {
    all: ["admissions"] as const,
    list: (params: object) => ["admissions", "list", params] as const,
    detail: (id: string) => ["admissions", "detail", id] as const,
  },
  audit: {
    all: ["audit"] as const,
    list: (params: object) => ["audit", "list", params] as const,
    stats: ["audit", "stats"] as const,
    modules: ["audit", "modules"] as const,
  },
  notifications: {
    all: ["notifications"] as const,
    list: (params: object) => ["notifications", "list", params] as const,
    unreadCount: ["notifications", "unread-count"] as const,
  },
};
